baseURL = "https://tflatischler.github.io/tflatischler-blog/"
locale = 'de-at'
title = 'Tim Flatischler'
theme = "archie"

[params]
  primaryColor = "#2E86AB"
  accentColor = "#F6A623"
  highlightColor = "#FFCC00"
  bgColor = "#181A1B"
  textColor = "#FFEEC9"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/athul/archie"

[outputs]
  home = ["html", "rss"]
  section = ["html", "rss"]
  taxonomy = ["html"]  # Deaktiviert RSS für Taxonomien
  term = ["html"]      # Deaktiviert RSS für Term-Seiten   

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3
