baseURL = "https://tflatischler.github.io/tflatischler-blog/"
locale = 'de-at'
title = 'tflatischler'
theme = "archie"

[params]
  primaryColor = "#2E86AB"
  accentColor = "#F6A623"
  highlightColor = "#FFCC00"
  bgColor = "#181A1B"
  textColor = "#FFEEC9"
